### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ji1996** [ZhangZhuoSJTU/Web3Bugs#13]
We noticed that the paper mentions the distribution of bugs in different types of projects, i.e. Lending, Dexes, etc. Is this part of the dataset available?
Thanks!

**Comment by ZhangZhuoSJTU** [comment]
Certainly. 

The file `results/contests.csv` contains the project types that are associated with the corresponding project IDs, while the file `results/bugs.csv` contains the bug types that are associated with the same project IDs. By utilizing this information, we are able to obtain distributions. 

It should be noted that [our dataset has been updated](https://github.com/ZhangZhuoSJTU/Web3Bugs/blob/main/docs/classification.md), as well as our classification standards. Therefore, the results may vary slightly from those that were reported in the paper.

**Comment by ZhangZhuoSJTU** [comment]
Hi @ji1996,

I wanted to let you know that I have made some updates to a script that retrieves the distribution. You can access the updated script [here](https://github.com/ZhangZhuoSJTU/Web3Bugs/blob/main/scripts/get_distribution.py).

If you have any further concerns or require any additional assistance, please don't hesitate to let me know.

**Comment by ji1996** [comment]
Thanks for your answer, it solved my qusestion!
